#airth.py
a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print("=================================================")
print("AIRTHMATIC OPERSTION IS")
print("=================================================")
print("\t{}+{}={}".format(a,b,a+b))
print("\t{}-{}={}".format(a,b,a-b))
print("\t{}*{}={}".format(a,b,a*b))
print("\t{}/{}={}".format(a,b,a/b))
print("\t{}//{}={}".format(a,b,a//b))
print("\t{}%{}={}".format(a,b,a%b))
print("\t{}**{}={}".format(a,b,a**b))
print("=================================================")