#swap.py
a=int(input("enter first number:"))
b=int(input("enter second number:"))
print("="*40)
print("before swapping")
print("="*40)
print("First number is={}".format(a))
print("second number is={}".format(b))
print("="*40)
a,b=b,a
print("="*40)
print("after swapping")
print("="*40)
print("First number is={}".format(a))
print("second number is={}".format(b))
print("="*40)